### PR TITLE
Ignore _BBN if isn't a PCI root bus

### PR DESCRIPTION
**Pull request by RicardoLuis0**
aims to fix issue #75 , tested on the system that caused the issue, works as intended, may need more testing on non-bugged systems to make sure there are no regressions.

### CODE REVIEW

**Comment by thomtl** [comment]
This assumes that all PCI root busses have the names PCI{0 -> 9} which is not something guaranteed by spec

**Comment by RicardoLuis0** [comment]
hmm... is at least the "PCI" part mandated by the spec?

**Comment by thomtl** [comment]
No, all names mandated by spec start with an underscore. The correct way of fixing this would be to check if there is a root bus PNP ID, we discussed this in the discord channel.

**Comment by RicardoLuis0** [comment]
i'll read up on that, then try to implement a proper fix, thanks for the pointers!

**Comment by RicardoLuis0** [comment]
seems the _CID is "PNP0A03" (according to [microsoft docs](http://download.microsoft.com/download/1/6/1/161ba512-40e2-4cc9-843a-923143f3456c/devids.txt) ), haven't found the _HID though

**Comment by RicardoLuis0** [comment]
tested on VMs, and the buggy laptop, seems to be working? might need testing on a machine where _BBN actually does something

**Comment by RicardoLuis0** [comment]
nvm i must've misunderstood something, it isn't working actually...

**Comment by RicardoLuis0** [comment]
fixed it not working

**Comment by RicardoLuis0** [comment]
bump? if it's not at all possible to merge this, can someone else at least implement another fix? issue #75 is seriously affecting my laptop and i'd rather not keep using a custom fork to run on it if i can...

**Comment by avdgrinten** [comment]
Hm, you're right that we should prioritize this since it potentially breaks a lot of setups. I will take a look in the next few days.

**Comment by RicardoLuis0** [comment]
alternate fix implemented in #82

**Pull request closed without merging**
